name: Check app.py Quality

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ " " ]

jobs:
  lint:
    name: Lint and Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint

      - name: Run flake8
        run: flake8 app.py --max-line-length=120 --ignore=E501,W503

      - name: Run pylint
        run: pylint app.py --disable=C0114,C0115,C0116 --fail-under=8.0